name: models

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.1.8
  built_value: ^8.1.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  built_value_generator: ^8.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5

flutter: null
