include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    depend_on_referenced_packages: false
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
