name: mobile
description: Akiflow Mobile
publish_to: "none"

version: 2.38.01+413

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies: 
  async: ^2.9.0  
  equatable: ^2.0.3
  flutter:
    sdk: flutter 
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter 
  flutter_quill: ^7.1.16
  flutter_rounded_date_picker: ^3.0.2
  flutter_segment: ^3.9.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  get_it: ^7.2.0
  html: ^0.15.0
  http: ^1.1.0
  i18n:
    path: ./packages/i18n
  #intercom_flutter: ^7.6.2
  intl: ^0.18.0
  modal_bottom_sheet:
     git:
       url: https://github.com/followthemoney1/modal_bottom_sheet.git
       ref: main
       path: modal_bottom_sheet
  models:
    path: ./packages/models  
  package_info_plus: ^4.0.2
  rrule: ^0.2.8
  sentry_flutter: ^7.8.0
  shared_preferences: ^2.0.17
  sqflite: ^2.2.8+4
  table_calendar: ^3.0.5
  timeago: ^3.2.2
  tuple: ^2.0.0
  url_launcher: ^6.0.20 
  uuid: ^3.0.6
  visibility_detector: ^0.3.3
  webview_flutter: ^4.2.2
  flutter_appauth: ^6.0.1
  dio: ^5.2.1+1
  share_handler: ^0.0.16
  device_preview: ^1.1.0 
  timezone: ^0.9.0
  syncfusion_calendar:
    path: ./packages/syncfusion_calendar
  flutter_local_notifications: ^15.1.0+1
  workmanager: ^0.5.1 
  firebase_messaging: ^14.2.2
  firebase_core: ^2.5.0
  flutter_displaymode: ^0.6.0
  platform_device_id: ^1.0.1 
  extended_text_field: ^12.0.1
  flutter_native_timezone: ^2.0.0
  flutter_js: any
  just_audio: ^0.9.34
  pusher_channels_flutter: ^2.1.2
  app_links: ^3.4.2
  numberpicker: ^2.1.2
  dotted_border: ^2.0.0+3
  quill_html_editor: ^2.2.2
  audio_session: ^0.1.16
  flutter_isolate: ^2.0.4
  #html_editor_enhanced: ^2.5.1

  
  
dev_dependencies:
  flutter_launcher_icons_maker: ^0.10.1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.2

flutter_native_splash:
  color: "#FAFBFD"
  image: "assets/images/akiflow_icon.png"
  android: true
  ios: true

flutter_icons:
  android: false # update from android assets directly (flutter_icons padding issue)
  ios: true
  image_path_ios: "assets/images/akiflow_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/fonts/
    - assets/images/
    - assets/images/app_icon/
    - assets/images/akiflow/
    - assets/images/favicons/
    - assets/images/icons/
    - assets/images/icons/_common/
    - assets/images/icons/google/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/icons/_common/
    - assets/images/icons/asana/
    - assets/images/icons/clickup/
    - assets/images/icons/dropbox/
    - assets/images/icons/github/
    - assets/images/icons/google/
    - assets/images/icons/jira/
    - assets/images/icons/notion/
    - assets/images/icons/slack/
    - assets/images/icons/superhuman/
    - assets/images/icons/todoist/
    - assets/images/icons/trello/
    - assets/images/icons/twitter/
    - assets/images/icons/web/
    - assets/images/icons/zapier/
    - assets/images/icons/zoom/
    - assets/html/
    - assets/js/chrono-custom-rules-master/
    - assets/js/chrono-custom-rules-master/dist/
    - assets/sounds/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
