name: mobile
description: Akiflow Mobile
publish_to: "none"
version: 0.5.1+9

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_appauth: ^2.4.1
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  flutter_widget_from_html: ^0.8.5
  get_it: ^7.2.0
  http: ^0.13.4
  i18n:
    path: ./packages/i18n
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  jiffy: ^5.0.0
  models:
    path: ./packages/models
  package_info_plus: ^1.4.2
  path: ^1.8.0
  path_provider: ^2.0.9
  reorderables: ^0.4.4
  sentry_flutter: ^6.4.0
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2
  table_calendar: ^3.0.5
  timeago: ^3.2.2
  url_launcher: ^6.0.20
  uuid: ^3.0.6

dev_dependencies:
  flutter_launcher_icons_maker: "^0.10.1"
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.3+1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logo/logo_outline_512x512.png"
  image_path_ios: "assets/images/logo/logo_back_white.png"

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/fonts/
    - assets/images/
    - assets/images/akiflow/
    - assets/images/defaults/
    - assets/images/favicons/
    - assets/images/gratifications/
    - assets/images/help/
    - assets/images/icons/
    - assets/images/icons/_common/
    - assets/images/icons/google/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/popup/
    - assets/images/icons/
    - assets/images/icons/_common/
    - assets/images/icons/asana/
    - assets/images/icons/clickup/
    - assets/images/icons/dropbox/
    - assets/images/icons/google/
    - assets/images/icons/jira/
    - assets/images/icons/microsoft/
    - assets/images/icons/notion/
    - assets/images/icons/slack/
    - assets/images/icons/superhuman/
    - assets/images/icons/todoist/
    - assets/images/icons/trello/
    - assets/images/icons/twitter/
    - assets/images/icons/zapier/
    - assets/images/icons/zoom/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
