name: mobile
description: Akiflow Mobile
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_widget_from_html: ^0.8.5
  get_it: ^7.2.0
  http: ^0.13.4
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  jiffy: ^5.0.0
  path: ^1.8.0
  path_provider: ^2.0.9
  sembast: ^3.2.0
  sentry_flutter: ^6.4.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  uuid: ^3.0.6

dev_dependencies:
  fast_i18n: ^5.12.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.3+1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/fonts/
    - assets/images/
    - assets/images/akiflow/
    - assets/images/defaults/
    - assets/images/favicons/
    - assets/images/gratifications/
    - assets/images/help/
    - assets/images/icons/
    - assets/images/icons/google/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/popup/
