class TzUtils {
  static String? toUtcStringIfNotNull(DateTime? date) {
    if (date == null) {
      return null;
    }

    return date.toUtc().toIso8601String();
  }
}

class LocalizationAbbreviations {
  static const abbreviations = {
    'Australia/Adelaide': {"dst": 'acdt', "default": 'acst'},
    'Australia/Broken_Hill': {"dst": 'acdt', "default": 'acst'},
    'Australia/Darwin': {"dst": 'acdt', "default": 'acst'},
    'Australia/North': {"dst": 'acdt', "default": 'acst'},
    'Australia/South': {"dst": 'acdt', "default": 'acst'},
    'Australia/Yancowinna': {"dst": 'acdt', "default": 'acst'},
    'America/Porto_Acre': {"dst": 'acst', "default": 'act'},
    'America/Eirunepe': {"dst": 'acst', "default": 'act'},
    'America/Rio_Branco': {"dst": 'acst', "default": 'act'},
    'Brazil/Acre': {"dst": 'acst', "default": 'act'},
    'Asia/Jayapura': {"default": 'wit'},
    'Australia/Eucla': {"dst": 'acwdt', "default": 'acwst'},
    'America/Goose_Bay': {"dst": 'adt', "default": 'ast'},
    'America/Pangnirtung': {"dst": 'edt', "default": 'est'},
    'America/Halifax': {"dst": 'adt', "default": 'ast'},
    'America/Barbados': {"dst": 'adt', "default": 'ast'},
    'America/Blanc-Sablon': {"dst": 'adt', "default": 'ast'},
    'America/Glace_Bay': {"dst": 'adt', "default": 'ast'},
    'America/Martinique': {"dst": 'adt', "default": 'ast'},
    'America/Moncton': {"dst": 'adt', "default": 'ast'},
    'America/Thule': {"dst": 'adt', "default": 'ast'},
    'Atlantic/Bermuda': {"dst": 'adt', "default": 'ast'},
    'Canada/Atlantic': {"dst": 'adt', "default": 'apt'},
    'Asia/Baghdad': {"dst": 'adt', "default": 'ast'},
    'Australia/Melbourne': {"dst": 'aedt', "default": 'aest'},
    'Antarctica/Macquarie': {"dst": 'aedt', "default": 'mist'},
    'Australia/ACT': {"dst": 'aedt', "default": 'aest'},
    'Australia/Brisbane': {"dst": 'aedt', "default": 'aest'},
    'Australia/Canberra': {"dst": 'aedt', "default": 'aest'},
    'Australia/Currie': {"dst": 'aedt', "default": 'aest'},
    'Australia/Hobart': {"dst": 'aedt', "default": 'aest'},
    'Australia/Lindeman': {"dst": 'aedt', "default": 'aest'},
    'Australia/NSW': {"dst": 'aedt', "default": 'aest'},
    'Australia/Queensland': {"dst": 'aedt', "default": 'aest'},
    'Australia/Sydney': {"dst": 'aedt', "default": 'aest'},
    'Australia/Tasmania': {"dst": 'aedt', "default": 'aest'},
    'Australia/Victoria': {"dst": 'aedt', "default": 'aest'},
    'Australia/LHI': {"default": 'aest', "dst": 'lhdt'},
    'Australia/Lord_Howe': {"default": 'lhst', "dst": 'lhdt'},
    'Asia/Kabul': {"default": 'aft'},
    'America/Anchorage': {"dst": 'akdt', "default": 'akst'},
    'America/Adak': {"default": 'hst', "dst": 'hdt'},
    'America/Atka': {"default": 'ahst', "dst": 'bdt'},
    'America/Juneau': {"dst": 'akdt', "default": 'akst'},
    'America/Metlakatla': {"dst": 'akdt', "default": 'akst'},
    'America/Nome': {"dst": 'akdt', "default": 'akst'},
    'America/Sitka': {"dst": 'akdt', "default": 'akst'},
    'America/Yakutat': {"dst": 'akdt', "default": 'akst'},
    'America/Boa_Vista': {"dst": 'amst', "default": 'amt'},
    'America/Campo_Grande': {"dst": 'amst', "default": 'amt'},
    'America/Cuiaba': {"dst": 'amst', "default": 'amt'},
    'America/Manaus': {"dst": 'amst', "default": 'amt'},
    'America/Porto_Velho': {"dst": 'amst', "default": 'amt'},
    'America/Santarem': {"dst": 'amst', "default": 'brt'},
    'Brazil/West': {"dst": 'amst', "default": 'amt'},
    'America/Asuncion': {"default": 'pyt', "dst": 'pyst'},
    'Europe/Amsterdam': {"default": 'cet', "dst": 'cest'},
    'Europe/Athens': {"default": 'eet', "dst": 'eest'},
    'America/Curacao': {"default": 'ast'},
    'America/Aruba': {"default": 'ast'},
    'America/Kralendijk': {"default": 'ast'},
    'America/Lower_Princes': {"default": 'ast'},
    'America/Puerto_Rico': {"dst": 'apt', "default": 'ast'},
    'America/Buenos_Aires': {"dst": 'arst', "default": 'arst'},
    'America/Argentina/Buenos_Aires': {"dst": 'arst', "default": 'art'},
    'America/Argentina/Catamarca': {"dst": 'arst', "default": 'art'},
    'America/Argentina/ComodRivadavia': {"dst": 'arst', "default": 'arst'},
    'America/Argentina/Cordoba': {"dst": 'arst', "default": 'art'},
    'America/Argentina/Jujuy': {"dst": 'arst', "default": 'art'},
    'America/Argentina/La_Rioja': {"dst": 'arst', "default": 'art'},
    'America/Argentina/Mendoza': {"dst": 'arst', "default": 'art'},
    'America/Argentina/Rio_Gallegos': {"dst": 'arst', "default": 'art'},
    'America/Argentina/Salta': {"dst": 'arst', "default": 'art'},
    'America/Argentina/San_Juan': {"dst": 'arst', "default": 'art'},
    'America/Argentina/San_Luis': {"dst": 'arst', "default": 'art'},
    'America/Argentina/Tucuman': {"dst": 'arst', "default": 'art'},
    'America/Argentina/Ushuaia': {"dst": 'arst', "default": 'art'},
    'America/Catamarca': {"dst": 'arst', "default": 'arst'},
    'America/Cordoba': {"dst": 'arst', "default": 'arst'},
    'America/Jujuy': {"dst": 'arst', "default": 'arst'},
    'America/Mendoza': {"dst": 'arst', "default": 'arst'},
    'America/Rosario': {"dst": 'arst', "default": 'arst'},
    'Antarctica/Palmer': {"dst": 'clst', "default": 'clt'},
    'Asia/Riyadh': {"default": 'ast'},
    'America/Anguilla': {"default": 'ast'},
    'America/Antigua': {"default": 'ast'},
    'America/Dominica': {"default": 'ast'},
    'America/Grand_Turk': {"default": 'ast', "dst": 'edt'},
    'America/Grenada': {"default": 'ast'},
    'America/Guadeloupe': {"default": 'ast'},
    'America/Marigot': {"default": 'ast'},
    'America/Miquelon': {"default": 'pmst', "dst": 'pmdt'},
    'America/Montserrat': {"default": 'ast'},
    'America/Port_of_Spain': {"default": 'ast'},
    'America/Santo_Domingo': {"default": 'ast', "dst": 'edt'},
    'America/St_Barthelemy': {"default": 'ast'},
    'America/St_Kitts': {"default": 'ast'},
    'America/St_Lucia': {"default": 'ast'},
    'America/St_Thomas': {"default": 'ast'},
    'America/St_Vincent': {"default": 'ast'},
    'America/Tortola': {"default": 'ast'},
    'America/Virgin': {"default": 'ast'},
    'Asia/Aden': {"default": 'ast'},
    'Asia/Bahrain': {"default": 'ast'},
    'Asia/Kuwait': {"default": 'ast'},
    'Asia/Qatar': {"default": 'ast'},
    'Australia/Perth': {"dst": 'awdt', "default": 'awst'},
    'Australia/West': {"dst": 'awdt', "default": 'awst'},
    'Atlantic/Azores': {"dst": 'azost', "default": 'azot'},
    'Europe/London': {"dst": 'bst', "default": 'gmt'},
    'Asia/Dacca': {"dst": 'bdst', "default": 'bdt'},
    'Asia/Dhaka': {"dst": 'bdst', "default": 'bdt'},
    'Europe/Belfast': {"dst": 'bdst', "default": 'bst'},
    'Europe/Gibraltar': {"dst": 'cest', "default": 'cet'},
    'Europe/Guernsey': {"dst": 'bst', "default": 'gmt'},
    'Europe/Isle_of_Man': {"dst": 'bst', "default": 'gmt'},
    'Europe/Jersey': {"dst": 'bst', "default": 'gmt'},
    "GB": {"dst": 'bdst', "default": 'bst'},
    'Africa/Mogadishu': {"default": 'eat'},
    'Africa/Addis_Ababa': {"default": 'eat'},
    'Africa/Asmara': {"default": 'eat'},
    'Africa/Asmera': {"default": 'beat'},
    'Africa/Dar_es_Salaam': {"default": 'eat'},
    'Africa/Djibouti': {"default": 'eat'},
    'Africa/Kampala': {"default": 'eat'},
    'Africa/Nairobi': {"default": 'eat'},
    'Indian/Antananarivo': {"default": 'eat'},
    'Indian/Comoro': {"default": 'eat'},
    'Indian/Mayotte': {"default": 'eat'},
    'Europe/Tiraspol': {"default": 'bmt', "dst": 'cest'},
    'America/Bogota': {"default": 'cot', "dst": 'cost'},
    'Europe/Brussels': {"default": 'cet', "dst": 'cest'},
    'Europe/Busingen': {"default": 'cet', "dst": 'cest'},
    'Europe/Vaduz': {"default": 'cet', "dst": 'cest'},
    'Europe/Zurich': {"default": 'cet', "dst": 'cest'},
    'Asia/Bangkok': {"default": 'ict'},
    'Asia/Phnom_Penh': {"default": 'ict'},
    'Asia/Vientiane': {"default": 'ict'},
    'Asia/Jakarta': {"default": 'wib'},
    'Europe/Bucharest': {"default": 'eet', "dst": 'eest'},
    'Europe/Chisinau': {"default": 'eet', "dst": 'eest'},
    'Asia/Brunei': {"default": 'bnt'},
    'Asia/Kuching': {"dst": 'bortst', "default": 'myt'},
    'America/La_Paz': {"dst": 'bost', "default": 'bot'},
    'America/Sao_Paulo': {"dst": 'brst', "default": 'brt'},
    'America/Araguaina': {"dst": 'brst', "default": 'brt'},
    'America/Bahia': {"dst": 'brst', "default": 'brt'},
    'America/Belem': {"dst": 'brst', "default": 'brt'},
    'America/Fortaleza': {"dst": 'brst', "default": 'brt'},
    'America/Maceio': {"dst": 'brst', "default": 'brt'},
    'America/Recife': {"dst": 'brst', "default": 'brt'},
    'Brazil/East': {"dst": 'brst', "default": 'brt'},
    'Pacific/Midway': {"default": 'sst'},
    'Pacific/Pago_Pago': {"default": 'sst'},
    'Pacific/Samoa': {"default": 'bst'},
    'Europe/Dublin': {"dst": 'ist', "default": 'gmt'},
    'Pacific/Bougainville': {"default": 'bst'},
    'Asia/Thimbu': {"default": 'btt'},
    'Asia/Thimphu': {"default": 'btt'},
    'Asia/Kolkata': {"default": 'ist', "dst": 'ist'},
    'Asia/Calcutta': {"default": 'burt', "dst": 'ist'},
    'Asia/Rangoon': {"default": 'burt'},
    'Asia/Yangon': {"default": 'mmt'},
    'Atlantic/Canary': {"default": 'wet', "dst": 'west'},
    'Africa/Juba': {"dst": 'cast', "default": 'eat'},
    'Africa/Khartoum': {"dst": 'cast', "default": 'eat'},
    'Africa/Blantyre': {"default": 'cat'},
    'Africa/Bujumbura': {"default": 'cat'},
    'Africa/Gaborone': {"default": 'cat'},
    'Africa/Harare': {"default": 'cat'},
    'Africa/Kigali': {"default": 'cat'},
    'Africa/Lubumbashi': {"default": 'cat'},
    'Africa/Lusaka': {"default": 'cat'},
    'Africa/Maputo': {"default": 'cat'},
    'Africa/Windhoek': {"default": 'wat', "dst": 'wast'},
    'Indian/Cocos': {"default": 'cct'},
    'America/Rankin_Inlet': {"dst": 'cdt', "default": 'cst'},
    'America/Resolute': {"dst": 'cdt', "default": 'cst'},
    'America/Chicago': {"dst": 'cdt', "default": 'cst'},
    'Asia/Shanghai': {"dst": 'cdt', "default": 'cst'},
    'America/Havana': {"dst": 'cdt', "default": 'cst'},
    'America/Atikokan': {"dst": 'cdt', "default": 'est'},
    'America/Bahia_Banderas': {"dst": 'cdt', "default": 'cst'},
    'America/Belize': {"dst": 'cdt', "default": 'cst'},
    'America/Cambridge_Bay': {"dst": 'mdt', "default": 'mst'},
    'America/Cancun': {"dst": 'cdt', "default": 'est'},
    'America/Chihuahua': {"dst": 'mdt', "default": 'mst'},
    'America/Coral_Harbour': {"dst": 'cdt', "default": 'cpt'},
    'America/Costa_Rica': {"dst": 'cdt', "default": 'cst'},
    'America/El_Salvador': {"dst": 'cdt', "default": 'cst'},
    'America/Fort_Wayne': {"dst": 'cdt', "default": 'cpt'},
    'America/Guatemala': {"dst": 'cdt', "default": 'cst'},
    'America/Indiana/Indianapolis': {"dst": 'edt', "default": 'est'},
    'America/Indiana/Knox': {"dst": 'cdt', "default": 'cst'},
    'America/Indiana/Marengo': {"dst": 'edt', "default": 'est'},
    'America/Indiana/Petersburg': {"dst": 'edt', "default": 'est'},
    'America/Indiana/Tell_City': {"dst": 'cdt', "default": 'cst'},
    'America/Indiana/Vevay': {"dst": 'edt', "default": 'est'},
    'America/Indiana/Vincennes': {"dst": 'edt', "default": 'est'},
    'America/Indiana/Winamac': {"dst": 'edt', "default": 'est'},
    'America/Indianapolis': {"dst": 'cdt', "default": 'cpt'},
    'America/Iqaluit': {"dst": 'edt', "default": 'est'},
    'America/Kentucky/Louisville': {"dst": 'edt', "default": 'est'},
    'America/Kentucky/Monticello': {"dst": 'edt', "default": 'est'},
    'America/Knox_IN': {"dst": 'cdt', "default": 'cpt'},
    'America/Louisville': {"dst": 'cdt', "default": 'cpt'},
    'America/Managua': {"dst": 'cdt', "default": 'cst'},
    'America/Matamoros': {"dst": 'cdt', "default": 'cst'},
    'America/Menominee': {"dst": 'cdt', "default": 'cst'},
    'America/Merida': {"dst": 'cdt', "default": 'cst'},
    'America/Mexico_City': {"dst": 'cdt', "default": 'cst'},
    'America/Monterrey': {"dst": 'cdt', "default": 'cst'},
    'America/North_Dakota/Beulah': {"dst": 'cdt', "default": 'cst'},
    'America/North_Dakota/Center': {"dst": 'cdt', "default": 'cst'},
    'America/North_Dakota/New_Salem': {"dst": 'cdt', "default": 'cst'},
    'America/Ojinaga': {"dst": 'mdt', "default": 'mst'},
    'America/Rainy_River': {"dst": 'cdt', "default": 'cst'},
    'America/Tegucigalpa': {"dst": 'cdt', "default": 'cst'},
    'America/Winnipeg': {"dst": 'cdt', "default": 'cst'},
    'Canada/Central': {"dst": 'cdt', "default": 'cpt'},
    'Mexico/General': {"dst": 'cdt', "default": 'cst'},
    'Asia/Chongqing': {"dst": 'cdt', "default": 'cst'},
    'Asia/Chungking': {"dst": 'cdt', "default": 'cst'},
    'Asia/Harbin': {"dst": 'cdt', "default": 'cst'},
    'Asia/Taipei': {"dst": 'cdt', "default": 'cst'},
    "PRC": {"dst": 'cdt', "default": 'cst'},
    "ROC": {"dst": 'cdt', "default": 'cst'},
    'Europe/Berlin': {"dst": 'cest', "default": 'cet'},
    'Europe/Kaliningrad': {"dst": 'cest', "default": 'eet'},
    'Africa/Algiers': {"dst": 'cest', "default": 'cet'},
    'Africa/Ceuta': {"dst": 'cest', "default": 'cet'},
    'Africa/Tripoli': {"dst": 'cest', "default": 'eet'},
    'Africa/Tunis': {"dst": 'cest', "default": 'cet'},
    'Arctic/Longyearbyen': {"dst": 'cest', "default": 'cet'},
    'Atlantic/Jan_Mayen': {"dst": 'cest', "default": 'cet'},
    'Europe/Andorra': {"dst": 'cest', "default": 'cet'},
    'Europe/Belgrade': {"dst": 'cest', "default": 'cet'},
    'Europe/Bratislava': {"dst": 'cest', "default": 'cet'},
    'Europe/Budapest': {"dst": 'cest', "default": 'cet'},
    'Europe/Copenhagen': {"dst": 'cest', "default": 'cet'},
    'Europe/Kiev': {"dst": 'eest', "default": 'eet'},
    'Europe/Lisbon': {"dst": 'west', "default": 'wet'},
    'Europe/Ljubljana': {"dst": 'cest', "default": 'cet'},
    'Europe/Luxembourg': {"dst": 'cest', "default": 'cet'},
    'Europe/Madrid': {"dst": 'cest', "default": 'cet'},
    'Europe/Malta': {"dst": 'cest', "default": 'cet'},
    'Europe/Minsk': {"dst": 'cest', "default": 'cet'},
    'Europe/Monaco': {"dst": 'cest', "default": 'cet'},
    'Europe/Oslo': {"dst": 'cest', "default": 'cet'},
    'Europe/Paris': {"dst": 'cest', "default": 'cet'},
    'Europe/Podgorica': {"dst": 'cest', "default": 'cet'},
    'Europe/Prague': {"dst": 'cest', "default": 'cet'},
    'Europe/Riga': {"dst": 'eest', "default": 'eet'},
    'Europe/Rome': {"dst": 'cest', "default": 'cet'},
    'Europe/San_Marino': {"dst": 'cest', "default": 'cet'},
    'Europe/Sarajevo': {"dst": 'cest', "default": 'cet'},
    'Europe/Simferopol': {"dst": 'cest', "default": 'msk'},
    'Europe/Skopje': {"dst": 'cest', "default": 'cet'},
    'Europe/Sofia': {"dst": 'eest', "default": 'eet'},
    'Europe/Stockholm': {"dst": 'cest', "default": 'cet'},
    'Europe/Tallinn': {"dst": 'eest', "default": 'eet'},
    'Europe/Tirane': {"dst": 'cest', "default": 'cet'},
    'Europe/Uzhgorod': {"dst": 'eest', "default": 'eet'},
    'Europe/Vatican': {"dst": 'cest', "default": 'cet'},
    'Europe/Vienna': {"dst": 'cest', "default": 'cet'},
    'Europe/Vilnius': {"dst": 'eest', "default": 'eet'},
    'Europe/Warsaw': {"dst": 'cest', "default": 'cet'},
    'Europe/Zagreb': {"dst": 'cest', "default": 'cet'},
    'Europe/Zaporozhye': {"dst": 'eest', "default": 'eet'},
    'Africa/Casablanca': {"default": 'wet', "dst": 'west'},
    'America/Scoresbysund': {"dst": 'egst', "default": 'egt'},
    'Pacific/Chatham': {"dst": 'chadt', "default": 'chast'},
    'Asia/Choibalsan': {"dst": 'chost', "default": 'chot'},
    'Pacific/Chuuk': {"default": 'chut'},
    'Pacific/Truk': {"default": 'chut'},
    'Pacific/Yap': {"default": 'chut'},
    'Pacific/Rarotonga': {"dst": 'ckhst', "default": 'ckt'},
    'America/Santiago': {"dst": 'clst', "default": 'clt'},
    'Chile/Continental': {"dst": 'clst', "default": 'clst'},
    'America/Caracas': {"default": 'vet'},
    'America/Cayman': {"default": 'est'},
    'America/Panama': {"default": 'est'},
    'America/Detroit': {"default": 'est', "dst": 'edt'},
    'America/Hermosillo': {"default": 'mst', "dst": 'mdt'},
    'America/Mazatlan': {"default": 'mst', "dst": 'mdt'},
    'America/Regina': {"default": 'cst', "dst": 'mdt'},
    'America/Swift_Current': {"default": 'cst', "dst": 'mdt'},
    'America/Thunder_Bay': {"default": 'est', "dst": 'edt'},
    'Canada/East-Saskatchewan': {"default": 'cst', "dst": 'mdt'},
    'Canada/Saskatchewan': {"default": 'cst', "dst": 'mdt'},
    'Mexico/BajaSur': {"default": 'cst', "dst": 'mdt'},
    'Asia/Macao': {"default": 'cst', "dst": 'most'},
    'Asia/Macau': {"default": 'cst', "dst": 'most'},
    'Atlantic/Cape_Verde': {"dst": 'cvst', "default": 'cvt'},
    'Indian/Christmas': {"default": 'cxt'},
    'Pacific/Guam': {"default": 'chst'},
    'Pacific/Saipan': {"default": 'chst'},
    'Chile/EasterIsland': {"dst": 'easst', "default": 'easst'},
    'Pacific/Easter': {"dst": 'easst', "default": 'east'},
    'America/Guayaquil': {"default": 'ect'},
    'Pacific/Galapagos': {"default": 'galt'},
    'America/New_York': {"dst": 'edt', "default": 'est'},
    'America/Jamaica': {"dst": 'edt', "default": 'est'},
    'America/Montreal': {"dst": 'edt', "default": 'ept'},
    'America/Nassau': {"dst": 'edt', "default": 'est'},
    'America/Nipigon': {"dst": 'edt', "default": 'est'},
    'America/Port-au-Prince': {"dst": 'edt', "default": 'est'},
    'America/Toronto': {"dst": 'edt', "default": 'est'},
    'Canada/Eastern': {"dst": 'edt', "default": 'ept'},
    'Europe/Helsinki': {"dst": 'eest', "default": 'eet'},
    'Africa/Cairo': {"dst": 'eest', "default": 'eet'},
    'Asia/Amman': {"dst": 'eest', "default": 'eet'},
    'Asia/Beirut': {"dst": 'eest', "default": 'eet'},
    'Asia/Damascus': {"dst": 'eest', "default": 'eet'},
    'Asia/Gaza': {"dst": 'eest', "default": 'eet'},
    'Asia/Hebron': {"dst": 'eest', "default": 'eet'},
    'Asia/Istanbul': {"dst": 'eest', "default": 'eet'},
    'Asia/Nicosia': {"dst": 'eest', "default": 'eet'},
    'Europe/Istanbul': {"dst": 'eest', "default": 'eet'},
    'Europe/Mariehamn': {"dst": 'eest', "default": 'eet'},
    'Europe/Moscow': {"dst": 'eest', "default": 'msk'},
    'Europe/Nicosia': {"dst": 'eest', "default": 'eet'},
    'Pacific/Fiji': {"dst": 'fjst', "default": 'fjt'},
    'Atlantic/Stanley': {"dst": 'fkst', "default": 'fkst'},
    'Atlantic/Madeira': {"default": 'wet', "dst": 'west'},
    'America/Noronha': {"dst": 'fnst', "default": 'fnt'},
    'Brazil/DeNoronha': {"dst": 'fnst', "default": 'fnt'},
    'Pacific/Gambier': {"default": 'gamt'},
    'America/Guyana': {"default": 'gyt'},
    'America/Cayenne': {"default": 'gft'},
    'Africa/Accra': {"dst": 'ghst', "default": 'gmt'},
    'Pacific/Tarawa': {"default": 'gilt'},
    'Africa/Abidjan': {"default": 'gmt'},
    'Africa/Bamako': {"default": 'gmt'},
    'Africa/Banjul': {"default": 'gmt'},
    'Africa/Bissau': {"default": 'gmt'},
    'Africa/Conakry': {"default": 'gmt'},
    'Africa/Dakar': {"default": 'gmt'},
    'Africa/Freetown': {"default": 'gmt'},
    'Africa/Lome': {"default": 'gmt'},
    'Africa/Monrovia': {"default": 'gmt'},
    'Africa/Nouakchott': {"default": 'gmt'},
    'Africa/Ouagadougou': {"default": 'gmt'},
    'Africa/Sao_Tome': {"default": 'gmt'},
    'Africa/Timbuktu': {"default": 'gmt'},
    'America/Danmarkshavn': {"default": 'gmt', "dst": 'wgst'},
    'Atlantic/Reykjavik': {"default": 'gmt', "dst": 'isst'},
    'Atlantic/St_Helena': {"default": 'gmt'},
    'Etc/GMT': {"default": 'gmt'},
    'Etc/Greenwich': {"default": 'gmt'},
    'Asia/Dubai': {"default": 'gst'},
    'Atlantic/South_Georgia': {"default": 'gst'},
    'Asia/Muscat': {"default": 'gst'},
    'Pacific/Honolulu': {"dst": 'hdt', "default": 'hst'},
    'Pacific/Johnston': {"dst": 'hdt', "default": 'hst'},
    'Asia/Hong_Kong': {"dst": 'hkst', "default": 'hkt'},
    'Asia/Hovd': {"dst": 'hovst', "default": 'hovt'},
    'Asia/Ho_Chi_Minh': {"default": 'ict'},
    'Asia/Saigon': {"default": 'ict'},
    'Asia/Jerusalem': {
      "dst": 'israel', // 'idt'
      "default": 'israel' // 'ist'
    },
    'Asia/Tel_Aviv': {"dst": 'iddt', "default": 'idt'},
    'Asia/Colombo': {"dst": 'ihst', "default": 'ist'},
    'Asia/Irkutsk': {"default": 'imt'},
    'Indian/Chagos': {"default": 'iot'},
    'Asia/Tehran': {"dst": 'irdt', "default": 'irst'},
    'Asia/Karachi': {"default": 'pkt', "dst": 'ist'},
    'Asia/Kathmandu': {"default": 'npt'},
    'Asia/Katmandu': {"default": 'ist'},
    'Asia/Pyongyang': {"default": 'kst'},
    'Asia/Seoul': {"default": 'kst', "dst": 'kdt'},
    'Asia/Tokyo': {"default": 'jst', "dst": 'jdt'},
    "ROK": {"default": 'jcst', "dst": 'kdt'},
    'Asia/Dili': {"default": 'tlt'},
    'Asia/Kuala_Lumpur': {"default": 'myt', "dst": 'malst'},
    'Asia/Makassar': {"default": 'wita'},
    'Asia/Manila': {"default": 'pht', "dst": 'phst'},
    'Asia/Pontianak': {"default": 'wib'},
    'Asia/Singapore': {"default": 'sgt', "dst": 'malst'},
    'Asia/Ujung_Pandang': {"default": 'jst'},
    'Pacific/Nauru': {"default": 'nrt'},
    'Pacific/Kosrae': {"default": 'kost'},
    'Pacific/Kwajalein': {"default": 'mht'},
    'Pacific/Kiritimati': {"default": 'lint'},
    'Pacific/Marquesas': {"default": 'mart'},
    'America/Yellowknife': {"dst": 'mdt', "default": 'mst'},
    'America/Denver': {"dst": 'mdt', "default": 'mst'},
    'America/Boise': {"dst": 'mdt', "default": 'mst'},
    'America/Edmonton': {"dst": 'mdt', "default": 'mst'},
    'America/Inuvik': {"dst": 'mdt', "default": 'mst'},
    'America/Phoenix': {"dst": 'mdt', "default": 'mst'},
    'America/Shiprock': {"dst": 'mdt', "default": 'mpt'},
    'Canada/Mountain': {"dst": 'mdt', "default": 'mpt'},
    "MET": {"dst": 'mest', "default": 'met'},
    'Pacific/Majuro': {"default": 'mht'},
    'America/Montevideo': {"default": 'uyt', "dst": 'uyhst'},
    'Indian/Maldives': {"default": 'mvt'},
    'America/Creston': {"default": 'mst'},
    'America/Dawson_Creek': {"default": 'mst', "dst": 'pdt'},
    'America/Ensenada': {"default": 'mst', "dst": 'pdt'},
    'America/Fort_Nelson': {"default": 'mst', "dst": 'pdt'},
    'America/Santa_Isabel': {"default": 'mst', "dst": 'pdt'},
    'America/Tijuana': {"default": 'pst', "dst": 'pdt'},
    'Mexico/BajaNorte': {"default": 'mst', "dst": 'pdt'},
    'Indian/Mauritius': {"dst": 'must', "default": 'mut'},
    'Pacific/Noumea': {"dst": 'ncst', "default": 'nct'},
    'America/St_Johns': {"dst": 'ndt', "default": 'nst'},
    'Canada/Newfoundland': {"dst": 'nddt', "default": 'ndt'},
    'America/Paramaribo': {"default": 'srt'},
    'Pacific/Norfolk': {"dst": 'nfst', "default": 'nft'},
    'Pacific/Niue': {"default": 'nut'},
    'Pacific/Auckland': {"dst": 'nzdt', "default": 'nzst'},
    'Antarctica/McMurdo': {"dst": 'nzdt', "default": 'nzst'},
    'Antarctica/South_Pole': {"dst": 'nzdt', "default": 'nzmt'},
    "NZ": {"dst": 'nzdt', "default": 'nzmt'},
    'America/Los_Angeles': {"dst": 'pdt', "default": 'pst'},
    'America/Dawson': {"dst": 'pdt', "default": 'pst'},
    'America/Vancouver': {"dst": 'pdt', "default": 'pst'},
    'America/Whitehorse': {"dst": 'pdt', "default": 'pst'},
    'Canada/Pacific': {"dst": 'pdt', "default": 'ppt'},
    'Canada/Yukon': {"dst": 'pdt', "default": 'pst'},
    'America/Lima': {"dst": 'pest', "default": 'pet'},
    'Pacific/Port_Moresby': {"default": 'pgt'},
    'Pacific/Enderbury': {"default": 'phot'},
    'Asia/Yekaterinburg': {"default": 'pmt'},
    'Pacific/Pitcairn': {"default": 'pst'},
    'Pacific/Pohnpei': {"default": 'pont'},
    'Pacific/Ponape': {"default": 'pont'},
    'Pacific/Palau': {"default": 'pwt'},
    'Indian/Reunion': {"default": 'ret'},
    'Africa/Johannesburg': {"default": 'sast', "dst": 'sast'},
    'Africa/Maseru': {"dst": 'sast', "default": 'sast'},
    'Africa/Mbabane': {"dst": 'sast', "default": 'sast'},
    'Pacific/Guadalcanal': {"default": 'sbt'},
    'Indian/Mahe': {"default": 'sct'},
    'Pacific/Apia': {"dst": 'wsdt', "default": 'wsst'},
    'Pacific/Tahiti': {"default": 'taht'},
    'Asia/Tbilisi': {"default": 'tbmt'},
    'Pacific/Fakaofo': {"default": 'tkt'},
    'Pacific/Tongatapu': {"dst": 'tost', "default": 'tot'},
    'Pacific/Funafuti': {"default": 'tvt'},
    'Etc/UCT': {"default": 'uct'},
    'Asia/Ulaanbaatar': {"dst": 'ulast', "default": 'ulat'},
    'Asia/Ulan_Bator': {"dst": 'ulast', "default": 'ulat'},
    'Etc/Universal': {"default": 'utc'},
    'Etc/UTC': {"default": 'utc'},
    'Etc/Zulu': {"default": 'utc'},
    "UTC": {"default": 'utc'},
    'Pacific/Efate': {"dst": 'vust', "default": 'vut'},
    'Pacific/Wake': {"default": 'wakt'},
    'Africa/Ndjamena': {"dst": 'wast', "default": 'wat'},
    'Africa/Brazzaville': {"default": 'wat'},
    'Africa/El_Aaiun': {"default": 'wet', "dst": 'west'},
    'Africa/Bangui': {"default": 'wat'},
    'Africa/Douala': {"default": 'wat'},
    'Africa/Kinshasa': {"default": 'wat'},
    'Africa/Lagos': {"default": 'wat'},
    'Africa/Libreville': {"default": 'wat'},
    'Africa/Luanda': {"default": 'wat'},
    'Africa/Malabo': {"default": 'wat'},
    'Africa/Niamey': {"default": 'wat'},
    'Africa/Porto-Novo': {"default": 'wat'},
    'Atlantic/Faeroe': {"dst": 'west', "default": 'wet'},
    'Atlantic/Faroe': {"dst": 'west', "default": 'wet'},
    'Pacific/Wallis': {"default": 'wft'},
    'America/Godthab': {"dst": 'wgst', "default": 'wgt'},
    'Asia/Kashgar': {"default": 'xjt'},
    'Asia/Urumqi': {"default": 'xjt'}
  };
}
